### ISSUE TITLE
Allow configuring headlessness, ssh timeout, etc. from command line

### ISSUE THREAD

**Issue by benjamineskola** [nickcharlton/boxes#23]
The defaults are probably fine when simply building a box but it would be nice when debugging to be able to configure these. Setting a variable that's passed through to the ERB should be simple enough.

**Comment by nickcharlton** [comment]
So I've been thinking about this on and off and I'm not quite sure how to go about it (without making a mess of everything).

Currently, arguments go into `Boxes::Builder` and these should probably go in the same place (otherwise getting to it will be a massive jump). The trouble is that the first few are validated on. Adding more will make a mess of the code.

My thought was something along the lines of allowing for an args hash to `Boxes::Builder.new`. But then that complicates the templates. What do you think?

**Comment by kirjatoukka** [comment]
I feel like an ideal solution would allow arbitrary keys to be set. I wonder if a better way might be to treat the template as a data structure rather than a text file? It's JSON, after all, so then you could accept parameters like `-var this.that=foo` → `{"this": {"that": "foo"}}` perhaps.

**Comment by nickcharlton** [comment]
Yes, that'd add much more flexibility.

That feels like a `3.0.0` kind of change, though…
